/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('vexip-ui')['Button']
    Card: typeof import('vexip-ui')['Card']
    Column: typeof import('vexip-ui')['Column']
    ConfigProvider: typeof import('vexip-ui')['ConfigProvider']
    Divider: typeof import('vexip-ui')['Divider']
    Form: typeof import('vexip-ui')['Form']
    FormItem: typeof import('vexip-ui')['FormItem']
    H1: typeof import('vexip-ui')['H1']
    Icon: typeof import('vexip-ui')['Icon']
    Input: typeof import('vexip-ui')['Input']
    Linker: typeof import('vexip-ui')['Linker']
    RmcTree: typeof import('./src/components/RmcTree.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('vexip-ui')['Row']
    Tree: typeof import('vexip-ui')['Tree']
  }
}
